#A travis config that automate the test, build and deployment to AWS which will utilize Dockerrun.aws.json
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tommytang1995/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tommytang1995/react-test npm run test

after_success:
  - docker build -t tommytang1995/multi-client ./client
  - docker build -t tommytang1995/multi-nginx ./nginx
  - docker build -t tommytang1995/multi-server ./server
  - docker build -t tommytang1995/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push these images to docker hub
  - docker push tommytang1995/multi-client
  - docker push tommytang1995/multi-nginx
  - docker push tommytang1995/multi-server
  - docker push tommytang1995/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-715207321184'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY