language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tommytang1995/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tommytang1995/react-test npm run test

after_success:
  - docker build -t tommytang1995/multi-client ./client
  - docker build -t tommytang1995/multi-nginx ./nginx
  - docker build -t tommytang1995/multi-server ./server
  - docker build -t tommytang1995/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push these images to docker hub
  - docker push tommytang1995/multi-client
  - docker push tommytang1995/multi-nginx
  - docker push tommytang1995/multi-server
  - docker push tommytang1995/multi-worker